### ISSUE TITLE
请教QtWebEngineView中文路径问题

### ISSUE THREAD

**Issue by dakuhao** [songjt1993/QMLPrettyUI#1]
您好，从google上搜索到你也遇到Pyside2 QtWebEngineView中文路径问题

Evironment
Windows 10
PyQt5 5.14.2
PyQtWebEngine 5.14.0
PyInstaller 3.6
Bug Discription
I can successfully package the .exe file. the .exe file can alse work well in a full English path. But if the path has Chinese， the error occured “Could not find QtWebEngineProcess.exe”

请问你是如何解决的，望指教！

**Comment by songjt1993** [comment]
> xcopy <python安装库路径>\PyQt5\Qt\bin\QtWebEngineProcess.exe <包文件夹的根目录>
> xcopy <python安装库路径>\PyQt5\Qt\resources\* <包文件夹的根目录>

**Comment by dakuhao** [comment]
解决了，感谢感谢！
实测PySide2 解决方法也类似。

**Comment by HackHarry** [comment]
我把QtWebEngineProcess.exe和resources都复制过去了，然后遇到了下面这个报错，其中?D??是中文路径。
`Qt WebEngine resources not found at C:/Users/Admin/Desktop/test/?D??/test/PySide2/resources. Trying parent directory...`
请问有遇到过吗？

**Comment by monyuan** [comment]
> 我把QtWebEngineProcess.exe和resources都复制过去了，然后遇到了下面这个报错，其中?D??是中文路径。
> `Qt WebEngine resources not found at C:/Users/Admin/Desktop/test/?D??/test/PySide2/resources. Trying parent directory...`
> 请问有遇到过吗？

你解决了吗，我也遇到了

**Comment by jackwxs** [comment]
QtWebEngineProcess.exe 请问中文路径下找不到依赖是这么解决的

**Comment by jackwxs** [comment]
我现在是将整个 QtWebEngineProcess.exe 及其整个依赖考到电脑缓存目录下

**Comment by HackHarry** [comment]
> > 我把QtWebEngineProcess.exe和resources都复制过去了，然后遇到了下面这个报错，其中?D??是中文路径。
> > `Qt WebEngine resources not found at C:/Users/Admin/Desktop/test/?D??/test/PySide2/resources. Trying parent directory...`
> > 请问有遇到过吗？
> 
> 你解决了吗，我也遇到了

@monyuan QT5的bug，解析路径时未做utf-8处理。我向qt团队提issue，他们打算在qt6解决。

**Comment by Dittonal** [comment]
中文路径下使用pyside2出现Could not find QtWebEngineProcess.exe，全部改为英文路径运行就没问题了
